### ISSUE TITLE
Nesting isn't working with postcss-preset-env + postcss-cli

### ISSUE THREAD

**Issue by johngeorgewright** [jonathantneal/postcss-preset-env#16]
Hey there,

I'm struggling to get your preset to play nicely with `postcss-cli`. It doesn't want to do anything about nesting.

I installed your preset with the CLI:

```
npm i -D postcss-cli postcss-preset-env
```

Made a config file:

```js
// postcss.config.js
module.exports = {
  map: true,
  plugins: {
    'postcss-preset-env': {}
  }
}
```

Copied part of your README example into a CSS file:

```css
/* src/css/entry.css */
:root {
  --mainColor: #12345678;
}

a {
  color: rebeccapurple;

  &:hover {
    color: color-mod(var(--mainColor) alpha(80%));
  }
}
```

Ran the CLI:

```
postcss src/css/entry.css -o dist/css/app.css
```

Then when I take a look at the compiled file, the nesting hasn't changed:

```css
/* dist/css/app.css */
:root {
  --mainColor: rgba(18, 52, 86, 0.47059);
}

a {
  color: #639;

  &:hover {
    color: rgba(18, 52, 86, 0.8);
    color: rgba(18, 52, 86, 0.8);
  }
}

/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uLy4uL3NyYy9jc3MvZW50cnkuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBO0VBQ0UsdUNBQXVCO0NBQ3hCOztBQUVEO0VBQ0UsWUFBcUI7O0VBRXJCO0lBQ0UsNkJBQThDO0lBQTlDLDZCQUE4QztHQUMvQztDQUNGIiwiZmlsZSI6Im1vbC1hZHZlcnRzLmNzcyIsInNvdXJjZXNDb250ZW50IjpbIjpyb290IHtcbiAgLS1tYWluQ29sb3I6ICMxMjM0NTY3ODtcbn1cblxuYSB7XG4gIGNvbG9yOiByZWJlY2NhcHVycGxlO1xuXG4gICY6aG92ZXIge1xuICAgIGNvbG9yOiBjb2xvci1tb2QodmFyKC0tbWFpbkNvbG9yKSBhbHBoYSg4MCUpKTtcbiAgfVxufVxuIl19 */
```

I've tried using the Browserslist config:

```js
// postcss.config.js
module.exports = {
  map: true,
  plugins: {
    'postcss-preset-env': {
      browsers: 'last 2 versions'
    }
  }
}
```

And I've also tried specifying just the nesting plugin:

```js
// postcss.config.js
module.exports = {
  map: true,
  plugins: {
    'postcss-preset-env': {
      stage: false,
      features: [ 'css-nesting' ]
    }
  }
}
```

... Although the output changes when amending the config, there's no change to the **nested** output. Am I missing something obvious?
